[package]
name = "yex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "yex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
scoped_thread_local = "0.5.1"
yrs = "0.18.8"

[features]
default = ["nif_version_2_15"]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]
nif_version_2_17 = ["rustler/nif_version_2_17"]