[package]
name = "yex"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "yex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
scoped_thread_local = "0.5.1"
yrs = "0.18.8"
